name: release
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --release --locked --target=${{ matrix.target }} --color=always --verbose


      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: >
          7z a headset-controller-${{ matrix.target }}.zip
          ./target/${{ matrix.target }}/release/headset-controller.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            ./target/${{ matrix.target }}/release/clipboard-typer.exe
